travis:
  secure:
    BINSTAR_TOKEN: Npr00RXUsCbvLnjiAm/3scMNt/yiatAIB6Xg2piOg7GNAhMNA2UIGpbLihT/v2ifjwR9lT3Kvb8KOP8YoVFMrHNUhOfVHysQPWWCEDpQTNFtbHIyGgu6S+KUyYAWPPGeSSsKstOLXVi3vmCSGtNye12X2lbnDPONqBTlaZYFZkXp1LphvpVEGxaS2c7dimRuPw0tQj8ZDNqoJEYGVpoHBq1X3HcQdmvEuGhGhJZapvIr7g39luTSFwxI0gdz5uYUQYqgmudjFgvvyh1/kh5KAeWPm18FM4DEQg7qF9Jx2iNALC2d6psIzKimm1BlbjAAu4hMX4BhEdXA2rRu8TrY7SCNzNinCzoj5GbVNFao7M6oTjwd79RBTAprYE14Y4MToWMYp1rIrjGX8wPlyE8P0MhJgWUHcrTdOHyoSIxy802BjvJJ8hpyk/4XAKw1WI7fLQmZJySPGREo6zlMXDb7foejbNqzx9OtXDV3rwMiv19SPrsqXskM8Q4YfdCml4YdliTSDQD7iuqWe27a9J3SN7iam1dSuvQVc0S3OrJWPLa38d98UR1wxfOZg6jRop9VrSpS9d5njPhOpcuEJgv72Hg4EiIH0ci1PwbCkTqVNDPZKqe6C1h7nCsWrl+M8uXqsYepKWYyTca8IgNwVQfXu53WvGgNZ4RH08uRL+q6SMk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
