travis:
  secure:
    BINSTAR_TOKEN: nIMFtPS3H9w8JuLF9NbXNPHTFqmZZIHHuAuU88XaT/ZcMh7xoUC2GVWl6X9V3HZQQQTKeK8TJRsRvKPY0f4vLemP/XcC68aqYEh8fyVIvOiEQX6J2mfGhgJ3fnp7N/mk+O4/fcrhxMbn2OHz1aBsYATzCu6xIaMWQlrGU4J55eFHNc6XlzLT9nTxSFtkM24F5X6bMMszFqE6Bhpt5kGQYzTI6aetL53VEUjwGnqZxWwuv60gSsMEWroSHWT2yGCqlx1IjGScHZ6mtbJa8q9cjbp2u0am0g4aRQSQ+ak3a69Ubz8NkLNr6lbTX0nniSgCRCkbevXHIUaZE92kbo4TX8bPJFKrnPY5wY/2HxhOQCuiCDQNdNdYtHzxuEuuvDqaxpun5BNBWKt0mD1uJdZzWu3DVOpUJD4p1UxunxpGNYu4Ri5czm1yP8UBRB3E8nOnc8rORwobRies7vKsOXXsSm8eVNQEZiofNfsK8yzLpLEoVBok8fWyhAf0AlLAyYT6s0eopnZ4AHRl9z61OR/CsOqp/9M+IGs6EUmtGaQK2dCtCANtu1ijpkbruXxPE4S6S09Dq4QAA/zP89G+uhjqNSduNyl9/J94hsSk/Ssl412NkWtSmYtGtHqll+dEzroSCtijGCUCd9fiN1vWkQgQy1ZkPb8K6+4iRanajSB6Awg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
